# Generated by Django 2.2 on 2022-09-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_items_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartlist',
            old_name='card_is',
            new_name='card_id',
        ),
    ]
